theme: minima
title: Kristin Kurianski, Ph.D.
lang: en
#remote_theme: pages-themes/cayman@v0.2.0

#plugins:
#  - jekyll-remote-theme 
linkedin_username: 

header_pages:
- index.md
- about.md
- research.md
- teaching.md
- resources.md
